# Generated by Django 3.1.1 on 2020-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201012_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
