# Generated by Django 3.1.1 on 2020-10-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201016_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='current_bid',
        ),
    ]
