# Generated by Django 3.1.1 on 2020-10-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_listings_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='winner',
        ),
    ]
