# Generated by Django 3.1.1 on 2020-10-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listings_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Toys and Hobbies', 'TOYS AND HOBBIES'), ('Auto', 'AUTO'), ('Collectibles and Art', 'COLLECTIBLES AND ART'), ('Fashion', 'FASHION'), ('Sporting Goods', 'SPORTING GOODS'), ('Electronics', 'ELECTRONICS'), ('Home and Garden', 'HOME AND GARDEN'), ('Other', 'OTHER')], default='other', max_length=64),
        ),
    ]
